### ISSUE TITLE
Performance boost

### ISSUE THREAD

**Issue by rever96** [HexagonNico/GodotPlugin-FiniteStateMachine#1]
Hello,

I see that everytime `change_state` is called it perform a get_node.
I would suggest to list the states onready or on editor time.
I'm very new on godot (I'm from Unity) dunno what is the best way to make it.

It isn't?

**Comment by HexagonNico** [comment]
It's a good point. The reason why it performs a `get_node` is that I wanted the `change_state` function to take in the state's name as a parameter, but it is also possible to store all states in a dictionary on ready and retrieve them from that. I'll see if I can do that.

**Comment by HexagonNico** [comment]
I opted for the cache option. Now the `change_state` function will first check if there is a cached state with the given name and use that, otherwise it will get the state using `get_node`. This should sightly improve the performance when changing state.
